### ISSUE TITLE
Translated plurals don't seem actually handled by the PoEntry::get...() method family.

### ISSUE THREAD

**Issue by rulatir** [geekwright/Po#4]
The translated plurals don't seem to be actually handled by the PoEntry::get...() family of methods.

PoTokens::TRANSLATED_PLURAL has the value of 'msgstr['. The get() method simply uses the type argument to key the $this->entry array, however translated plurals are **not** stored in $this->entry under the key 'msgstr['. They are instead stored under the key 'msgstr' as an array-of-arrays. This can't work.

**Comment by geekwright** [comment]
The TRANSLATED_PLURAL token is used for parsing only. The data is retrieved as an array with the TRANSLATED token.

The get() method works on the raw data, which mimics the internal formatting of the po file, while the getAsString() and getAsStringArray() methods turn the data into usable strings. The presence of a non-empty PLURAL string is a signal that the TRANSLATED data should be expected to be an array. An example would be:

```
$msgid_plural = $entry->get(PoTokens::PLURAL);
if (empty($msgid_plural)) {
    $msgstr = $entry->getAsString(PoTokens::TRANSLATED);
} else {
    $msgstr = $entry->getAsStringArray(PoTokens::TRANSLATED);
}
```
